### ISSUE TITLE
Missing Python packages

### ISSUE THREAD

**Issue by tibfab** [dataiku/dss-plugin-reinforcement-learning#4]
Hi, installed the plugin incl. code environment successfully. However, if I run it I get the following error:

[14:39:43] [INFO] [dku.utils]  - *************** Recipe code failed **************
[14:39:43] [INFO] [dku.utils]  - Begin Python stack
[14:39:43] [INFO] [dku.utils]  - Traceback (most recent call last):
[14:39:43] [INFO] [dku.utils]  -   File "/media/dss-design-node-ebs/dss_data/jobs/QLEARNINGWITHDSS/Build_Saved_Models_2020-11-09T14-39-40.350/compute_mi6VwW1C_NP/custom-python-recipe/pyoutJQ9s2ba0SjCO/python-exec-wrapper.py", line 206, in <module>
[14:39:43] [INFO] [dku.utils]  -     exec(f.read())
[14:39:43] [INFO] [dku.utils]  -   File "<string>", line 10, in <module>
[14:39:43] [INFO] [dku.utils]  - ModuleNotFoundError: No module named 'stable_baselines_training_wrapper'

The list of installed packages in the code environment _plugin_reinforcement-learning_managed_ doesn't contain the package _stable_baselines_training_wrapper_, hence the error. What am I missing?
Could you please advise how to fix this and use the Plugin with success?

DSS version 8.0.2

Thanks

**Comment by tibfab** [comment]
After some debugging, I found out that the package _stable_baselines_training_wrapper_ is part of the plugin and based on the DSS logs, _sys..path_ points to the correct directory _...dss_data/plugins/dev/reinforcement-learning/python-lib_ from that the module should be loaded. But still no luck.

**Comment by tibfab** [comment]
Ok, I've figured it out. It was an ACL permission issue which blocked the user (job owner) from reading the plugin directory (having DSS User Isolation Framework activated). 
Fixed that as _admin_ by the use of _setfacl_.
